<?php
use Symfony\Cmf\Component\Routing\RouteObjectInterface;

/**
 * Implements djustable_titles_preprocess_html().
 *
 * Adds additional information to html variables.
 *
 */

function adjustable_titles_preprocess_html(&$variables) {

  $request = \Drupal::request();

  if ($request->attributes->has('node')) {
    if ($node = \Drupal\adjustable_titles\get_node()) {
      // Our trigger for whether adjustable titles should be used is currently this field.
      // It would be better to have an admin-populated set of page/content types.
      if (isset($node->field_header_image)) {
        $variables['attributes']['class'][] = 'has-adjustable-title';
      }
    }
  }
  if ($request->attributes->has('node')) {
    $node = $request->attributes->get('node');


  }

  if($request->attributes->has('taxonomy_term')) {

    $term = $request->attributes->get('taxonomy_term');
    $term_id = $term->get('tid')->value;
    $term_object = taxonomy_term_load($term_id);

    if (isset($term_object->field_header_image)) {
      $variables['attributes']['class'][] = 'has-adjustable-title';
    }
  }

}

/**
 * Implements adjustable_titles_preprocess_page_title().
 *
 * Adds additional information to title variables.
 *
 */

function adjustable_titles_preprocess_page_title(&$variables) {

  $request = \Drupal::request();

  // Pages

  if ($request->attributes->has('node')) {

    $node = $request->attributes->get('node');
    $node_type = $node->getType();
    $is_page = node_is_page($node);

    if ($is_page && ($node_type == 'page' || $node_type == 'service')) {

      $variables['adjustable_title']['title'] = $node->title[0]->value;
      $variables['adjustable_title']['images']['background_src'] = '/themes/cflassy/images/services-header-default.jpg';

      if (count($node->field_header_image) > 0) {
        $variables['adjustable_title']['images']['background_src'] = $node->field_header_image[0]->entity->uri->value;
      }

      if (count($node->body[0]) > 0) {
        $variables['adjustable_title']['summary'] = $node->body[0]->summary;
      }

    }
  }

  // Taxonomy Terms

  if ($request->attributes->has('taxonomy_term')) {

    $term = $request->attributes->get('taxonomy_term');

    //dump($term);

    $term_id = $term->get('tid')->value;
    $term_object = taxonomy_term_load($term_id);
    $header_image_file = '/themes/cflassy/images/services-header-default.jpg';

    $variables['adjustable_title']['title'] = $term->get('name')->value;

    if ($term->bundle()) {
      $header_image_field = \Drupal\field\Entity\FieldConfig::loadByName('taxonomy_term', 'services', 'field_header_image');
      $default_image = $header_image_field->getSetting('default_image');
      $header_image_file_entity = \Drupal::entityManager()->loadEntityByUuid('file', $default_image['uuid']);
      $header_image_file = $header_image_file_entity->getFileUri();

      if ($term->bundle() == 'services') {
        if (count($term_object->field_card_image[0]) > 0) {
          $variables['adjustable_title']['images']['icon'] = $term_object->field_card_image[0]->entity->uri->value;
        }
      }

    }

    $variables['adjustable_title']['images']['background_src'] = $header_image_file;

    if (count($term_object->field_tag_line[0]) > 0) {
      $variables['adjustable_title']['summary'] = $term->get('field_tag_line')->value;
    }

    if (count($term_object->field_header_image[0]) > 0) {
      $variables['adjustable_title']['images']['background_src'] = $term_object->field_header_image[0]->entity->uri->value;
    }

  }

}

/**
 * Implements hook_theme_suggestions_page_title_alter().
 */
function adjustable_titles_theme_suggestions_page_title_alter(array &$suggestions, array $variables) {

  $suggestions[] = 'page_title__adjustable_titles';

}
