<?php

/**
 * Implements hook_theme().
 */
function adjustable_titles_theme($existing, $type, $theme, $path) {
  return array(
    'page_title__adjustable' => array(
      'variables' => array('title' => NULL),
    ),
  );
}

/**
 * Implements hook_display_variant_plugin_alter().
 */
function adjustable_titles_display_variant_plugin_alter(array &$definitions) {
    $definitions['block_page']['class'] = \Drupal\adjustable_titles\Plugin\DisplayVariant\BlockPageVariant::class;
}